# Generated by Django 6.0.7 on 2026-07-22 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_delete_challenge_delete_contest_delete_deepwikiterm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_lessons',
        ),
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.CharField(default='book-open', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(default='10 Hours', max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.CharField(default='15 mins', max_length=20),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.unit'),
            preserve_default=False,
        ),
    ]
