# Generated by Django 6.0.7 on 2026-07-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_remove_course_total_lessons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='unit',
        ),
    ]
