# Generated by Django 6.0.7 on 2026-07-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_lessons',
            field=models.IntegerField(default=12),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
