# Generated by Django 6.0.7 on 2026-07-26 16:11

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_total_lessons_unit_lesson_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='Kontent'),
        ),
    ]
