# Generated by Django 6.0.7 on 2026-07-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lesson_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='xp_points',
        ),
    ]
