# Generated by Django 6.0.7 on 2026-07-29 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lessonfeedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
    ]
