# Generated by Django 6.0.7 on 2026-08-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_category_image_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
    ]
