# Generated by Django 6.0.7 on 2026-08-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(default='10 soat', max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.CharField(default='15 daqiqa', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tartib raqami'),
        ),
    ]
