# Generated by Django 6.0.7 on 2026-08-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_lesson_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
