# Generated by Django 6.0.7 on 2026-08-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_lesson_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.CharField(default='5 daqiqa', editable=False, help_text='Avtomatik hisoblanadi', max_length=30, verbose_name='Davomiyligi'),
        ),
    ]
