# Generated by Django 6.0.7 on 2026-07-22 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.CharField(blank=True, default='https://api.dicebear.com/7.x/bottts/svg?seed=Deepland', max_length=500)),
                ('bio', models.TextField(blank=True, default="Deepland platformasida AI va Dasturlash bo'yicha ta'lim olmoqda.")),
                ('xp_points', models.IntegerField(default=1500)),
                ('solved_challenges_count', models.IntegerField(default=12)),
                ('rank_title', models.CharField(default='AI Researcher', max_length=100)),
                ('github_url', models.URLField(blank=True, default='https://github.com')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
