# Generated by Django 6.0.7 on 2026-07-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='solved_challenges_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='xp_points',
        ),
    ]
