# Generated by Django 6.0.7 on 2026-08-04 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_solved_challenges_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, help_text='Qurilma nomi (masalan, iPhone 13, Windows PC)', max_length=255, null=True)),
                ('os_name', models.CharField(blank=True, help_text='Operatsion tizim', max_length=100, null=True)),
                ('browser', models.CharField(blank=True, help_text='Brauzer nomi', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP manzil', null=True)),
                ('location', models.CharField(blank=True, help_text="Qurilma manzili (masalan, Toshkent, O'zbekiston)", max_length=255, null=True)),
                ('session_key', models.CharField(blank=True, help_text='Django session kaliti', max_length=40, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Sessiya faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi sessiyasi',
                'verbose_name_plural': 'Foydalanuvchi sessiyalari',
                'ordering': ['-last_activity'],
            },
        ),
    ]
