# Generated by Django 6.0.7 on 2026-08-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Foydalanuvchi profili', 'verbose_name_plural': 'Foydalanuvchilar profillari'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://linkedin.com'),
        ),
    ]
