# Generated by Django 6.0.7 on 2026-08-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_options_userprofile_linkedin_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rank_title',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan foydalanuvchi'),
        ),
    ]
